sudo: required 
services:
   -docker 
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file service-account.json 
  - gcloud config set project eco-tract-275820
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials cluster-np
  - echo "$DOCKER_PASSOWRD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t paruchurink/estuary-web -f Dockerfile

script:
  - docker run paruchurink/estuary-web npm test -- --coverage
  

deploy:
  provider: script 
  script: bash ./deploy.sh
  on:
    branch: master  