apiVersion: v1
kind: Service
metadata:
  name: estuary-web-node-port
  namespace: estuary
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 8080
      nodePort: 30080	
  selector:
    app: estuary-web
